CREATE TABLE IF NOT EXISTS genres (
	id    int     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	genre varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS ratingsMPA (
	id     int     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	rating varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	id       bigint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name     varchar   NOT NULL,
	email    varchar   NOT NULL,
	login    varchar   NOT NULL,
	birthday timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS user_friends (
	user_id              bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	friend_id            bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS films (
	id           bigint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name         varchar    NOT NULL,
	description  varchar    NOT NULL,
	release_date timestamp  NOT NULL,
	duration     int        NOT NULL,
	rating_id    int        REFERENCES ratingsMPA(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
	film_id  bigint NOT NULL REFERENCES films(id) ON DELETE CASCADE,
	genre_id int    NOT NULL REFERENCES genres(id) ON DELETE CASCADE,
	PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_users_likes (
	film_id bigint NOT NULL REFERENCES films(id) ON DELETE CASCADE,
	user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	PRIMARY KEY (film_id, user_id)
);


